//go:build go1.22

// Package payment provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package payment

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorErrorCode.
const (
	ErrorErrorCodeBookingNotFound             ErrorErrorCode = "booking_not_found"
	ErrorErrorCodeBookingNotPayable           ErrorErrorCode = "booking_not_payable"
	ErrorErrorCodeIdempotencyKeyReuse         ErrorErrorCode = "idempotency_key_reuse"
	ErrorErrorCodeInternalError               ErrorErrorCode = "internal_error"
	ErrorErrorCodePaymentAlreadyExists        ErrorErrorCode = "payment_already_exists"
	ErrorErrorCodePaymentNotFound             ErrorErrorCode = "payment_not_found"
	ErrorErrorCodeProviderError               ErrorErrorCode = "provider_error"
	ErrorErrorCodeSignatureVerificationFailed ErrorErrorCode = "signature_verification_failed"
	ErrorErrorCodeUnauthenticated             ErrorErrorCode = "unauthenticated"
	ErrorErrorCodeUnauthorized                ErrorErrorCode = "unauthorized"
	ErrorErrorCodeValidationFailed            ErrorErrorCode = "validation_failed"
)

// Valid indicates whether the value is a known member of the ErrorErrorCode enum.
func (e ErrorErrorCode) Valid() bool {
	switch e {
	case ErrorErrorCodeBookingNotFound:
		return true
	case ErrorErrorCodeBookingNotPayable:
		return true
	case ErrorErrorCodeIdempotencyKeyReuse:
		return true
	case ErrorErrorCodeInternalError:
		return true
	case ErrorErrorCodePaymentAlreadyExists:
		return true
	case ErrorErrorCodePaymentNotFound:
		return true
	case ErrorErrorCodeProviderError:
		return true
	case ErrorErrorCodeSignatureVerificationFailed:
		return true
	case ErrorErrorCodeUnauthenticated:
		return true
	case ErrorErrorCodeUnauthorized:
		return true
	case ErrorErrorCodeValidationFailed:
		return true
	default:
		return false
	}
}

// Defines values for PaymentProvider.
const (
	PaymentProviderStripe PaymentProvider = "stripe"
)

// Valid indicates whether the value is a known member of the PaymentProvider enum.
func (e PaymentProvider) Valid() bool {
	switch e {
	case PaymentProviderStripe:
		return true
	default:
		return false
	}
}

// Defines values for PaymentStatus.
const (
	Failed    PaymentStatus = "failed"
	Pending   PaymentStatus = "pending"
	Succeeded PaymentStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the PaymentStatus enum.
func (e PaymentStatus) Valid() bool {
	switch e {
	case Failed:
		return true
	case Pending:
		return true
	case Succeeded:
		return true
	default:
		return false
	}
}

// Defines values for PaymentHealthz200JSONResponseBodyStatus.
const (
	PaymentHealthz200JSONResponseBodyStatusOk PaymentHealthz200JSONResponseBodyStatus = "ok"
)

// Valid indicates whether the value is a known member of the PaymentHealthz200JSONResponseBodyStatus enum.
func (e PaymentHealthz200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case PaymentHealthz200JSONResponseBodyStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for PaymentReadyz200JSONResponseBodyStatus.
const (
	PaymentReadyz200JSONResponseBodyStatusOk PaymentReadyz200JSONResponseBodyStatus = "ok"
)

// Valid indicates whether the value is a known member of the PaymentReadyz200JSONResponseBodyStatus enum.
func (e PaymentReadyz200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case PaymentReadyz200JSONResponseBodyStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for CreatePayment201JSONResponseBodyProvider.
const (
	CreatePayment201JSONResponseBodyProviderStripe CreatePayment201JSONResponseBodyProvider = "stripe"
)

// Valid indicates whether the value is a known member of the CreatePayment201JSONResponseBodyProvider enum.
func (e CreatePayment201JSONResponseBodyProvider) Valid() bool {
	switch e {
	case CreatePayment201JSONResponseBodyProviderStripe:
		return true
	default:
		return false
	}
}

// Defines values for HandleStripeWebhook200JSONResponseBodyReceived.
const (
	True HandleStripeWebhook200JSONResponseBodyReceived = true
)

// Valid indicates whether the value is a known member of the HandleStripeWebhook200JSONResponseBodyReceived enum.
func (e HandleStripeWebhook200JSONResponseBodyReceived) Valid() bool {
	switch e {
	case True:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Error struct {
		Code          ErrorErrorCode `json:"code"`
		CorrelationId string         `json:"correlation_id"`
		Details       *[]struct {
			Field string `json:"field"`
			Issue string `json:"issue"`
		} `json:"details,omitempty"`
		Message string `json:"message"`
	} `json:"error"`
}

// ErrorErrorCode defines model for Error.Error.Code.
type ErrorErrorCode string

// Payment Contains no card data by construction. `provider_payment_id` is a Stripe reference,
// not an instrument.
type Payment struct {
	// AmountMinor Read from the booking, in the currency's minor unit. Never client-supplied.
	AmountMinor int `json:"amount_minor"`

	// BookingId UUIDv7, string-typed everywhere
	//
	// Examples: 01912d5a-7f3e-7c1a-9b2e-3f4a5b6c7d8e
	BookingId Uuid      `json:"booking_id"`
	CreatedAt time.Time `json:"created_at"`
	Currency  string    `json:"currency"`

	// FailureCode Stripe's decline code when status is failed, e.g. card_declined
	FailureCode *string `json:"failure_code,omitempty"`

	// Id UUIDv7, string-typed everywhere
	//
	// Examples: 01912d5a-7f3e-7c1a-9b2e-3f4a5b6c7d8e
	Id       Uuid            `json:"id"`
	Provider PaymentProvider `json:"provider"`

	// ProviderPaymentId Stripe PaymentIntent id, e.g. pi_3Abc...
	ProviderPaymentId string `json:"provider_payment_id"`

	// Status pending   — PaymentIntent created, outcome unknown
	// succeeded — Stripe confirmed the charge (via webhook); terminal
	// failed    — Stripe declined or the intent was cancelled; terminal
	Status    PaymentStatus `json:"status"`
	UpdatedAt time.Time     `json:"updated_at"`
}

// PaymentProvider defines model for Payment.Provider.
type PaymentProvider string

// PaymentStatus pending   — PaymentIntent created, outcome unknown
// succeeded — Stripe confirmed the charge (via webhook); terminal
// failed    — Stripe declined or the intent was cancelled; terminal
type PaymentStatus string

// Uuid UUIDv7, string-typed everywhere
//
// Examples: 01912d5a-7f3e-7c1a-9b2e-3f4a5b6c7d8e
type Uuid = openapi_types.UUID

// CorrelationId defines model for CorrelationId.
type CorrelationId = string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ServerError defines model for ServerError.
type ServerError = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// PaymentHealthz200JSONResponseBodyStatus defines parameters for PaymentHealthz.
type PaymentHealthz200JSONResponseBodyStatus string

// PaymentReadyz200JSONResponseBodyStatus defines parameters for PaymentReadyz.
type PaymentReadyz200JSONResponseBodyStatus string

// CreatePaymentJSONBody defines parameters for CreatePayment.
type CreatePaymentJSONBody struct {
	// BookingId UUIDv7, string-typed everywhere
	//
	// Examples: 01912d5a-7f3e-7c1a-9b2e-3f4a5b6c7d8e
	BookingId Uuid `json:"booking_id"`
}

// CreatePaymentParams defines parameters for CreatePayment.
type CreatePaymentParams struct {
	// XCorrelationId Propagated unchanged through every downstream call, event, log line, and span.
	XCorrelationId *CorrelationId `json:"X-Correlation-Id,omitempty"`

	// IdempotencyKey Client-generated unique key, passed through to Stripe's own idempotency. Mandatory:
	// a retried charge without one is a double-charge.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreatePayment201JSONResponseBodyProvider defines parameters for CreatePayment.
type CreatePayment201JSONResponseBodyProvider string

// GetPaymentParams defines parameters for GetPayment.
type GetPaymentParams struct {
	// XCorrelationId Propagated unchanged through every downstream call, event, log line, and span.
	XCorrelationId *CorrelationId `json:"X-Correlation-Id,omitempty"`
}

// HandleStripeWebhookJSONBody defines parameters for HandleStripeWebhook.
type HandleStripeWebhookJSONBody struct {
	Data map[string]interface{} `json:"data"`

	// Id Stripe event id — the idempotency key for this handler
	Id string `json:"id"`

	// Type e.g. payment_intent.succeeded, payment_intent.payment_failed
	Type string `json:"type"`
}

// HandleStripeWebhookParams defines parameters for HandleStripeWebhook.
type HandleStripeWebhookParams struct {
	// StripeSignature HMAC signature. Verified before the body is trusted.
	StripeSignature string `json:"Stripe-Signature"`
}

// HandleStripeWebhook200JSONResponseBodyReceived defines parameters for HandleStripeWebhook.
type HandleStripeWebhook200JSONResponseBodyReceived bool

// CreatePaymentJSONRequestBody defines body for CreatePayment for application/json ContentType.
type CreatePaymentJSONRequestBody CreatePaymentJSONBody

// HandleStripeWebhookJSONRequestBody defines body for HandleStripeWebhook for application/json ContentType.
type HandleStripeWebhookJSONRequestBody HandleStripeWebhookJSONBody

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// PaymentHealthz Liveness probe
	//
	// Corresponds with GET /healthz (the `PaymentHealthz` operationId).
	PaymentHealthz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PaymentReadyz Readiness probe — checks database and broker connectivity
	//
	// Corresponds with GET /readyz (the `PaymentReadyz` operationId).
	PaymentReadyz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreatePaymentWithBody Start a payment for a held booking
	//
	// Creates a Stripe PaymentIntent for the booking's authoritative amount and returns its
	// client secret so the browser can complete the charge directly with Stripe.
	//
	// Returns `pending`. The real outcome arrives asynchronously via the Stripe webhook,
	// which is what emits `PaymentSucceeded`/`PaymentFailed`. Do NOT treat a 201 here as a
	// successful payment.
	//
	// The amount is read from the booking — never from the request. A client-supplied
	// amount would let a customer set their own price.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/payments (the `CreatePayment` operationId).
	CreatePaymentWithBody(ctx context.Context, params *CreatePaymentParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreatePayment Start a payment for a held booking
	//
	// Creates a Stripe PaymentIntent for the booking's authoritative amount and returns its
	// client secret so the browser can complete the charge directly with Stripe.
	//
	// Returns `pending`. The real outcome arrives asynchronously via the Stripe webhook,
	// which is what emits `PaymentSucceeded`/`PaymentFailed`. Do NOT treat a 201 here as a
	// successful payment.
	//
	// The amount is read from the booking — never from the request. A client-supplied
	// amount would let a customer set their own price.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/payments (the `CreatePayment` operationId).
	CreatePayment(ctx context.Context, params *CreatePaymentParams, body CreatePaymentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPayment Get a payment's status
	//
	// Corresponds with GET /v1/payments/{payment_id} (the `GetPayment` operationId).
	GetPayment(ctx context.Context, paymentId Uuid, params *GetPaymentParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// HandleStripeWebhookWithBody Stripe payment outcome callback
	//
	// Called by Stripe, not by our clients. This is the authoritative source of payment
	// outcomes and the only path that emits `PaymentSucceeded`/`PaymentFailed`.
	//
	// **Authentication is by Stripe signature, not by our JWT** — hence `security: []`.
	// The `Stripe-Signature` header MUST be verified against STRIPE_WEBHOOK_SECRET before
	// the body is parsed or trusted. An unverified body is attacker-controlled input: it
	// would let anyone mark any booking paid.
	//
	// Stripe retries on non-2xx and may deliver duplicates, so handling is idempotent on
	// the Stripe event id. Unknown event types are acknowledged with 200 and ignored.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/webhooks/stripe (the `HandleStripeWebhook` operationId).
	HandleStripeWebhookWithBody(ctx context.Context, params *HandleStripeWebhookParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// HandleStripeWebhook Stripe payment outcome callback
	//
	// Called by Stripe, not by our clients. This is the authoritative source of payment
	// outcomes and the only path that emits `PaymentSucceeded`/`PaymentFailed`.
	//
	// **Authentication is by Stripe signature, not by our JWT** — hence `security: []`.
	// The `Stripe-Signature` header MUST be verified against STRIPE_WEBHOOK_SECRET before
	// the body is parsed or trusted. An unverified body is attacker-controlled input: it
	// would let anyone mark any booking paid.
	//
	// Stripe retries on non-2xx and may deliver duplicates, so handling is idempotent on
	// the Stripe event id. Unknown event types are acknowledged with 200 and ignored.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/webhooks/stripe (the `HandleStripeWebhook` operationId).
	HandleStripeWebhook(ctx context.Context, params *HandleStripeWebhookParams, body HandleStripeWebhookJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// PaymentHealthz Liveness probe
//
// Corresponds with GET /healthz (the `PaymentHealthz` operationId).
func (c *Client) PaymentHealthz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPaymentHealthzRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PaymentReadyz Readiness probe — checks database and broker connectivity
//
// Corresponds with GET /readyz (the `PaymentReadyz` operationId).
func (c *Client) PaymentReadyz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPaymentReadyzRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreatePaymentWithBody Start a payment for a held booking
//
// Creates a Stripe PaymentIntent for the booking's authoritative amount and returns its
// client secret so the browser can complete the charge directly with Stripe.
//
// Returns `pending`. The real outcome arrives asynchronously via the Stripe webhook,
// which is what emits `PaymentSucceeded`/`PaymentFailed`. Do NOT treat a 201 here as a
// successful payment.
//
// The amount is read from the booking — never from the request. A client-supplied
// amount would let a customer set their own price.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/payments (the `CreatePayment` operationId).
func (c *Client) CreatePaymentWithBody(ctx context.Context, params *CreatePaymentParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePaymentRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreatePayment Start a payment for a held booking
//
// Creates a Stripe PaymentIntent for the booking's authoritative amount and returns its
// client secret so the browser can complete the charge directly with Stripe.
//
// Returns `pending`. The real outcome arrives asynchronously via the Stripe webhook,
// which is what emits `PaymentSucceeded`/`PaymentFailed`. Do NOT treat a 201 here as a
// successful payment.
//
// The amount is read from the booking — never from the request. A client-supplied
// amount would let a customer set their own price.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/payments (the `CreatePayment` operationId).
func (c *Client) CreatePayment(ctx context.Context, params *CreatePaymentParams, body CreatePaymentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePaymentRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetPayment Get a payment's status
//
// Corresponds with GET /v1/payments/{payment_id} (the `GetPayment` operationId).
func (c *Client) GetPayment(ctx context.Context, paymentId Uuid, params *GetPaymentParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPaymentRequest(c.Server, paymentId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// HandleStripeWebhookWithBody Stripe payment outcome callback
//
// Called by Stripe, not by our clients. This is the authoritative source of payment
// outcomes and the only path that emits `PaymentSucceeded`/`PaymentFailed`.
//
// **Authentication is by Stripe signature, not by our JWT** — hence `security: []`.
// The `Stripe-Signature` header MUST be verified against STRIPE_WEBHOOK_SECRET before
// the body is parsed or trusted. An unverified body is attacker-controlled input: it
// would let anyone mark any booking paid.
//
// Stripe retries on non-2xx and may deliver duplicates, so handling is idempotent on
// the Stripe event id. Unknown event types are acknowledged with 200 and ignored.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/webhooks/stripe (the `HandleStripeWebhook` operationId).
func (c *Client) HandleStripeWebhookWithBody(ctx context.Context, params *HandleStripeWebhookParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHandleStripeWebhookRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// HandleStripeWebhook Stripe payment outcome callback
//
// Called by Stripe, not by our clients. This is the authoritative source of payment
// outcomes and the only path that emits `PaymentSucceeded`/`PaymentFailed`.
//
// **Authentication is by Stripe signature, not by our JWT** — hence `security: []`.
// The `Stripe-Signature` header MUST be verified against STRIPE_WEBHOOK_SECRET before
// the body is parsed or trusted. An unverified body is attacker-controlled input: it
// would let anyone mark any booking paid.
//
// Stripe retries on non-2xx and may deliver duplicates, so handling is idempotent on
// the Stripe event id. Unknown event types are acknowledged with 200 and ignored.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/webhooks/stripe (the `HandleStripeWebhook` operationId).
func (c *Client) HandleStripeWebhook(ctx context.Context, params *HandleStripeWebhookParams, body HandleStripeWebhookJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHandleStripeWebhookRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPaymentHealthzRequest constructs an http.Request for the PaymentHealthz method
func NewPaymentHealthzRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/healthz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPaymentReadyzRequest constructs an http.Request for the PaymentReadyz method
func NewPaymentReadyzRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/readyz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreatePaymentRequest calls the generic CreatePayment builder with application/json body
func NewCreatePaymentRequest(server string, params *CreatePaymentParams, body CreatePaymentJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreatePaymentRequestWithBody(server, params, "application/json", bodyReader)
}

// NewCreatePaymentRequestWithBody constructs an http.Request for the CreatePayment method, with any body, and a specified content type
func NewCreatePaymentRequestWithBody(server string, params *CreatePaymentParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/payments")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.XCorrelationId != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Correlation-Id", *params.XCorrelationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Correlation-Id", headerParam0)
		}

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithOptions("simple", false, "Idempotency-Key", params.IdempotencyKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Idempotency-Key", headerParam1)

	}

	return req, nil
}

// NewGetPaymentRequest constructs an http.Request for the GetPayment method
func NewGetPaymentRequest(server string, paymentId Uuid, params *GetPaymentParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "payment_id", paymentId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/payments/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.XCorrelationId != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Correlation-Id", *params.XCorrelationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Correlation-Id", headerParam0)
		}

	}

	return req, nil
}

// NewHandleStripeWebhookRequest calls the generic HandleStripeWebhook builder with application/json body
func NewHandleStripeWebhookRequest(server string, params *HandleStripeWebhookParams, body HandleStripeWebhookJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewHandleStripeWebhookRequestWithBody(server, params, "application/json", bodyReader)
}

// NewHandleStripeWebhookRequestWithBody constructs an http.Request for the HandleStripeWebhook method, with any body, and a specified content type
func NewHandleStripeWebhookRequestWithBody(server string, params *HandleStripeWebhookParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/webhooks/stripe")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Stripe-Signature", params.StripeSignature, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Stripe-Signature", headerParam0)

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// PaymentHealthzWithResponse Liveness probe
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /healthz (the `PaymentHealthz` operationId).
	PaymentHealthzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PaymentHealthzResponse, error)

	// PaymentReadyzWithResponse Readiness probe — checks database and broker connectivity
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /readyz (the `PaymentReadyz` operationId).
	PaymentReadyzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PaymentReadyzResponse, error)

	// CreatePaymentWithBodyWithResponse Start a payment for a held booking
	//
	// Creates a Stripe PaymentIntent for the booking's authoritative amount and returns its
	// client secret so the browser can complete the charge directly with Stripe.
	//
	// Returns `pending`. The real outcome arrives asynchronously via the Stripe webhook,
	// which is what emits `PaymentSucceeded`/`PaymentFailed`. Do NOT treat a 201 here as a
	// successful payment.
	//
	// The amount is read from the booking — never from the request. A client-supplied
	// amount would let a customer set their own price.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/payments (the `CreatePayment` operationId).
	CreatePaymentWithBodyWithResponse(ctx context.Context, params *CreatePaymentParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePaymentResponse, error)

	// CreatePaymentWithResponse Start a payment for a held booking
	//
	// Creates a Stripe PaymentIntent for the booking's authoritative amount and returns its
	// client secret so the browser can complete the charge directly with Stripe.
	//
	// Returns `pending`. The real outcome arrives asynchronously via the Stripe webhook,
	// which is what emits `PaymentSucceeded`/`PaymentFailed`. Do NOT treat a 201 here as a
	// successful payment.
	//
	// The amount is read from the booking — never from the request. A client-supplied
	// amount would let a customer set their own price.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/payments (the `CreatePayment` operationId).
	CreatePaymentWithResponse(ctx context.Context, params *CreatePaymentParams, body CreatePaymentJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePaymentResponse, error)

	// GetPaymentWithResponse Get a payment's status
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v1/payments/{payment_id} (the `GetPayment` operationId).
	GetPaymentWithResponse(ctx context.Context, paymentId Uuid, params *GetPaymentParams, reqEditors ...RequestEditorFn) (*GetPaymentResponse, error)

	// HandleStripeWebhookWithBodyWithResponse Stripe payment outcome callback
	//
	// Called by Stripe, not by our clients. This is the authoritative source of payment
	// outcomes and the only path that emits `PaymentSucceeded`/`PaymentFailed`.
	//
	// **Authentication is by Stripe signature, not by our JWT** — hence `security: []`.
	// The `Stripe-Signature` header MUST be verified against STRIPE_WEBHOOK_SECRET before
	// the body is parsed or trusted. An unverified body is attacker-controlled input: it
	// would let anyone mark any booking paid.
	//
	// Stripe retries on non-2xx and may deliver duplicates, so handling is idempotent on
	// the Stripe event id. Unknown event types are acknowledged with 200 and ignored.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/webhooks/stripe (the `HandleStripeWebhook` operationId).
	HandleStripeWebhookWithBodyWithResponse(ctx context.Context, params *HandleStripeWebhookParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*HandleStripeWebhookResponse, error)

	// HandleStripeWebhookWithResponse Stripe payment outcome callback
	//
	// Called by Stripe, not by our clients. This is the authoritative source of payment
	// outcomes and the only path that emits `PaymentSucceeded`/`PaymentFailed`.
	//
	// **Authentication is by Stripe signature, not by our JWT** — hence `security: []`.
	// The `Stripe-Signature` header MUST be verified against STRIPE_WEBHOOK_SECRET before
	// the body is parsed or trusted. An unverified body is attacker-controlled input: it
	// would let anyone mark any booking paid.
	//
	// Stripe retries on non-2xx and may deliver duplicates, so handling is idempotent on
	// the Stripe event id. Unknown event types are acknowledged with 200 and ignored.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/webhooks/stripe (the `HandleStripeWebhook` operationId).
	HandleStripeWebhookWithResponse(ctx context.Context, params *HandleStripeWebhookParams, body HandleStripeWebhookJSONRequestBody, reqEditors ...RequestEditorFn) (*HandleStripeWebhookResponse, error)
}

type PaymentHealthzResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		Status PaymentHealthz200JSONResponseBodyStatus `json:"status"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PaymentHealthzResponse) GetJSON200() *struct {
	Status PaymentHealthz200JSONResponseBodyStatus `json:"status"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r PaymentHealthzResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PaymentHealthzResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PaymentHealthzResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PaymentHealthzResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PaymentReadyzResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		Status PaymentReadyz200JSONResponseBodyStatus `json:"status"`
	}
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r PaymentReadyzResponse) GetJSON200() *struct {
	Status PaymentReadyz200JSONResponseBodyStatus `json:"status"`
} {
	return r.JSON200
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r PaymentReadyzResponse) GetJSON503() *Error {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r PaymentReadyzResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PaymentReadyzResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PaymentReadyzResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PaymentReadyzResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreatePaymentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *struct {
		// AmountMinor Read from the booking, in the currency's minor unit. Never client-supplied.
		AmountMinor int `json:"amount_minor"`

		// BookingId UUIDv7, string-typed everywhere
		//
		// Examples: 01912d5a-7f3e-7c1a-9b2e-3f4a5b6c7d8e
		BookingId Uuid `json:"booking_id"`

		// ClientSecret Stripe PaymentIntent client secret. Returned once, on creation only;
		// never persisted by us and never present on GET responses.
		ClientSecret string    `json:"client_secret"`
		CreatedAt    time.Time `json:"created_at"`
		Currency     string    `json:"currency"`

		// FailureCode Stripe's decline code when status is failed, e.g. card_declined
		FailureCode *string `json:"failure_code,omitempty"`

		// Id UUIDv7, string-typed everywhere
		//
		// Examples: 01912d5a-7f3e-7c1a-9b2e-3f4a5b6c7d8e
		Id       Uuid                                     `json:"id"`
		Provider CreatePayment201JSONResponseBodyProvider `json:"provider"`

		// ProviderPaymentId Stripe PaymentIntent id, e.g. pi_3Abc...
		ProviderPaymentId string `json:"provider_payment_id"`

		// Status pending   — PaymentIntent created, outcome unknown
		// succeeded — Stripe confirmed the charge (via webhook); terminal
		// failed    — Stripe declined or the intent was cancelled; terminal
		Status    PaymentStatus `json:"status"`
		UpdatedAt time.Time     `json:"updated_at"`
	}
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Error
	// JSON422 the response for an HTTP 422 `application/json` response
	JSON422 *Error
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *ServerError
	// JSON502 the response for an HTTP 502 `application/json` response
	JSON502 *Error
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r CreatePaymentResponse) GetJSON201() *struct {
	// AmountMinor Read from the booking, in the currency's minor unit. Never client-supplied.
	AmountMinor int `json:"amount_minor"`

	// BookingId UUIDv7, string-typed everywhere
	//
	// Examples: 01912d5a-7f3e-7c1a-9b2e-3f4a5b6c7d8e
	BookingId Uuid `json:"booking_id"`

	// ClientSecret Stripe PaymentIntent client secret. Returned once, on creation only;
	// never persisted by us and never present on GET responses.
	ClientSecret string    `json:"client_secret"`
	CreatedAt    time.Time `json:"created_at"`
	Currency     string    `json:"currency"`

	// FailureCode Stripe's decline code when status is failed, e.g. card_declined
	FailureCode *string `json:"failure_code,omitempty"`

	// Id UUIDv7, string-typed everywhere
	//
	// Examples: 01912d5a-7f3e-7c1a-9b2e-3f4a5b6c7d8e
	Id       Uuid                                     `json:"id"`
	Provider CreatePayment201JSONResponseBodyProvider `json:"provider"`

	// ProviderPaymentId Stripe PaymentIntent id, e.g. pi_3Abc...
	ProviderPaymentId string `json:"provider_payment_id"`

	// Status pending   — PaymentIntent created, outcome unknown
	// succeeded — Stripe confirmed the charge (via webhook); terminal
	// failed    — Stripe declined or the intent was cancelled; terminal
	Status    PaymentStatus `json:"status"`
	UpdatedAt time.Time     `json:"updated_at"`
} {
	return r.JSON201
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r CreatePaymentResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r CreatePaymentResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r CreatePaymentResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r CreatePaymentResponse) GetJSON409() *Error {
	return r.JSON409
}

// GetJSON422 returns the response for an HTTP 422 `application/json` response
func (r CreatePaymentResponse) GetJSON422() *Error {
	return r.JSON422
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r CreatePaymentResponse) GetJSON500() *ServerError {
	return r.JSON500
}

// GetJSON502 returns the response for an HTTP 502 `application/json` response
func (r CreatePaymentResponse) GetJSON502() *Error {
	return r.JSON502
}

// GetBody returns the raw response body bytes
func (r CreatePaymentResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreatePaymentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreatePaymentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreatePaymentResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetPaymentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Payment
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *ServerError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetPaymentResponse) GetJSON200() *Payment {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r GetPaymentResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r GetPaymentResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetPaymentResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r GetPaymentResponse) GetJSON500() *ServerError {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r GetPaymentResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetPaymentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPaymentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetPaymentResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type HandleStripeWebhookResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		Received HandleStripeWebhook200JSONResponseBodyReceived `json:"received"`
	}
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *ServerError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r HandleStripeWebhookResponse) GetJSON200() *struct {
	Received HandleStripeWebhook200JSONResponseBodyReceived `json:"received"`
} {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r HandleStripeWebhookResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r HandleStripeWebhookResponse) GetJSON500() *ServerError {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r HandleStripeWebhookResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r HandleStripeWebhookResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HandleStripeWebhookResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r HandleStripeWebhookResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// PaymentHealthzWithResponse Liveness probe
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /healthz (the `PaymentHealthz` operationId).
func (c *ClientWithResponses) PaymentHealthzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PaymentHealthzResponse, error) {
	rsp, err := c.PaymentHealthz(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePaymentHealthzResponse(rsp)
}

// PaymentReadyzWithResponse Readiness probe — checks database and broker connectivity
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /readyz (the `PaymentReadyz` operationId).
func (c *ClientWithResponses) PaymentReadyzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PaymentReadyzResponse, error) {
	rsp, err := c.PaymentReadyz(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePaymentReadyzResponse(rsp)
}

// CreatePaymentWithBodyWithResponse Start a payment for a held booking
//
// Creates a Stripe PaymentIntent for the booking's authoritative amount and returns its
// client secret so the browser can complete the charge directly with Stripe.
//
// Returns `pending`. The real outcome arrives asynchronously via the Stripe webhook,
// which is what emits `PaymentSucceeded`/`PaymentFailed`. Do NOT treat a 201 here as a
// successful payment.
//
// The amount is read from the booking — never from the request. A client-supplied
// amount would let a customer set their own price.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/payments (the `CreatePayment` operationId).
func (c *ClientWithResponses) CreatePaymentWithBodyWithResponse(ctx context.Context, params *CreatePaymentParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePaymentResponse, error) {
	rsp, err := c.CreatePaymentWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreatePaymentResponse(rsp)
}

// CreatePaymentWithResponse Start a payment for a held booking
//
// Creates a Stripe PaymentIntent for the booking's authoritative amount and returns its
// client secret so the browser can complete the charge directly with Stripe.
//
// Returns `pending`. The real outcome arrives asynchronously via the Stripe webhook,
// which is what emits `PaymentSucceeded`/`PaymentFailed`. Do NOT treat a 201 here as a
// successful payment.
//
// The amount is read from the booking — never from the request. A client-supplied
// amount would let a customer set their own price.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/payments (the `CreatePayment` operationId).
func (c *ClientWithResponses) CreatePaymentWithResponse(ctx context.Context, params *CreatePaymentParams, body CreatePaymentJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePaymentResponse, error) {
	rsp, err := c.CreatePayment(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreatePaymentResponse(rsp)
}

// GetPaymentWithResponse Get a payment's status
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /v1/payments/{payment_id} (the `GetPayment` operationId).
func (c *ClientWithResponses) GetPaymentWithResponse(ctx context.Context, paymentId Uuid, params *GetPaymentParams, reqEditors ...RequestEditorFn) (*GetPaymentResponse, error) {
	rsp, err := c.GetPayment(ctx, paymentId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPaymentResponse(rsp)
}

// HandleStripeWebhookWithBodyWithResponse Stripe payment outcome callback
//
// Called by Stripe, not by our clients. This is the authoritative source of payment
// outcomes and the only path that emits `PaymentSucceeded`/`PaymentFailed`.
//
// **Authentication is by Stripe signature, not by our JWT** — hence `security: []`.
// The `Stripe-Signature` header MUST be verified against STRIPE_WEBHOOK_SECRET before
// the body is parsed or trusted. An unverified body is attacker-controlled input: it
// would let anyone mark any booking paid.
//
// Stripe retries on non-2xx and may deliver duplicates, so handling is idempotent on
// the Stripe event id. Unknown event types are acknowledged with 200 and ignored.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/webhooks/stripe (the `HandleStripeWebhook` operationId).
func (c *ClientWithResponses) HandleStripeWebhookWithBodyWithResponse(ctx context.Context, params *HandleStripeWebhookParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*HandleStripeWebhookResponse, error) {
	rsp, err := c.HandleStripeWebhookWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHandleStripeWebhookResponse(rsp)
}

// HandleStripeWebhookWithResponse Stripe payment outcome callback
//
// Called by Stripe, not by our clients. This is the authoritative source of payment
// outcomes and the only path that emits `PaymentSucceeded`/`PaymentFailed`.
//
// **Authentication is by Stripe signature, not by our JWT** — hence `security: []`.
// The `Stripe-Signature` header MUST be verified against STRIPE_WEBHOOK_SECRET before
// the body is parsed or trusted. An unverified body is attacker-controlled input: it
// would let anyone mark any booking paid.
//
// Stripe retries on non-2xx and may deliver duplicates, so handling is idempotent on
// the Stripe event id. Unknown event types are acknowledged with 200 and ignored.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/webhooks/stripe (the `HandleStripeWebhook` operationId).
func (c *ClientWithResponses) HandleStripeWebhookWithResponse(ctx context.Context, params *HandleStripeWebhookParams, body HandleStripeWebhookJSONRequestBody, reqEditors ...RequestEditorFn) (*HandleStripeWebhookResponse, error) {
	rsp, err := c.HandleStripeWebhook(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHandleStripeWebhookResponse(rsp)
}

// ParsePaymentHealthzResponse parses an HTTP response from a PaymentHealthzWithResponse call
func ParsePaymentHealthzResponse(rsp *http.Response) (*PaymentHealthzResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PaymentHealthzResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Status PaymentHealthz200JSONResponseBodyStatus `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePaymentReadyzResponse parses an HTTP response from a PaymentReadyzWithResponse call
func ParsePaymentReadyzResponse(rsp *http.Response) (*PaymentReadyzResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PaymentReadyzResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Status PaymentReadyz200JSONResponseBodyStatus `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseCreatePaymentResponse parses an HTTP response from a CreatePaymentWithResponse call
func ParseCreatePaymentResponse(rsp *http.Response) (*CreatePaymentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreatePaymentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest struct {
			// AmountMinor Read from the booking, in the currency's minor unit. Never client-supplied.
			AmountMinor int `json:"amount_minor"`

			// BookingId UUIDv7, string-typed everywhere
			//
			// Examples: 01912d5a-7f3e-7c1a-9b2e-3f4a5b6c7d8e
			BookingId Uuid `json:"booking_id"`

			// ClientSecret Stripe PaymentIntent client secret. Returned once, on creation only;
			// never persisted by us and never present on GET responses.
			ClientSecret string    `json:"client_secret"`
			CreatedAt    time.Time `json:"created_at"`
			Currency     string    `json:"currency"`

			// FailureCode Stripe's decline code when status is failed, e.g. card_declined
			FailureCode *string `json:"failure_code,omitempty"`

			// Id UUIDv7, string-typed everywhere
			//
			// Examples: 01912d5a-7f3e-7c1a-9b2e-3f4a5b6c7d8e
			Id       Uuid                                     `json:"id"`
			Provider CreatePayment201JSONResponseBodyProvider `json:"provider"`

			// ProviderPaymentId Stripe PaymentIntent id, e.g. pi_3Abc...
			ProviderPaymentId string `json:"provider_payment_id"`

			// Status pending   — PaymentIntent created, outcome unknown
			// succeeded — Stripe confirmed the charge (via webhook); terminal
			// failed    — Stripe declined or the intent was cancelled; terminal
			Status    PaymentStatus `json:"status"`
			UpdatedAt time.Time     `json:"updated_at"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 502:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON502 = &dest

	}

	return response, nil
}

// ParseGetPaymentResponse parses an HTTP response from a GetPaymentWithResponse call
func ParseGetPaymentResponse(rsp *http.Response) (*GetPaymentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPaymentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Payment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseHandleStripeWebhookResponse parses an HTTP response from a HandleStripeWebhookWithResponse call
func ParseHandleStripeWebhookResponse(rsp *http.Response) (*HandleStripeWebhookResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HandleStripeWebhookResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Received HandleStripeWebhook200JSONResponseBodyReceived `json:"received"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// PaymentHealthz Liveness probe
	// (GET /healthz)
	PaymentHealthz(w http.ResponseWriter, r *http.Request)
	// PaymentReadyz Readiness probe — checks database and broker connectivity
	// (GET /readyz)
	PaymentReadyz(w http.ResponseWriter, r *http.Request)
	// CreatePayment Start a payment for a held booking
	// (POST /v1/payments)
	CreatePayment(w http.ResponseWriter, r *http.Request, params CreatePaymentParams)
	// GetPayment Get a payment's status
	// (GET /v1/payments/{payment_id})
	GetPayment(w http.ResponseWriter, r *http.Request, paymentId Uuid, params GetPaymentParams)
	// HandleStripeWebhook Stripe payment outcome callback
	// (POST /v1/webhooks/stripe)
	HandleStripeWebhook(w http.ResponseWriter, r *http.Request, params HandleStripeWebhookParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PaymentHealthz operation middleware
func (siw *ServerInterfaceWrapper) PaymentHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PaymentHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PaymentReadyz operation middleware
func (siw *ServerInterfaceWrapper) PaymentReadyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PaymentReadyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePayment operation middleware
func (siw *ServerInterfaceWrapper) CreatePayment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreatePaymentParams

	headers := r.Header

	// ------------- Optional header parameter "X-Correlation-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Correlation-Id")]; found {
		var XCorrelationId CorrelationId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Correlation-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Correlation-Id", valueList[0], &XCorrelationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Correlation-Id", Err: err})
			return
		}

		params.XCorrelationId = &XCorrelationId

	}

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePayment(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPayment operation middleware
func (siw *ServerInterfaceWrapper) GetPayment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "payment_id" -------------
	var paymentId Uuid

	err = runtime.BindStyledParameterWithOptions("simple", "payment_id", r.PathValue("payment_id"), &paymentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "payment_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPaymentParams

	headers := r.Header

	// ------------- Optional header parameter "X-Correlation-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Correlation-Id")]; found {
		var XCorrelationId CorrelationId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Correlation-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Correlation-Id", valueList[0], &XCorrelationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Correlation-Id", Err: err})
			return
		}

		params.XCorrelationId = &XCorrelationId

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPayment(w, r, paymentId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HandleStripeWebhook operation middleware
func (siw *ServerInterfaceWrapper) HandleStripeWebhook(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params HandleStripeWebhookParams

	headers := r.Header

	// ------------- Required header parameter "Stripe-Signature" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Stripe-Signature")]; found {
		var StripeSignature string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Stripe-Signature", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Stripe-Signature", valueList[0], &StripeSignature, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Stripe-Signature", Err: err})
			return
		}

		params.StripeSignature = StripeSignature

	} else {
		err := fmt.Errorf("Header parameter Stripe-Signature is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Stripe-Signature", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HandleStripeWebhook(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.PaymentHealthz)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/readyz", wrapper.PaymentReadyz)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/payments", wrapper.CreatePayment)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/payments/{payment_id}", wrapper.GetPayment)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/webhooks/stripe", wrapper.HandleStripeWebhook)

	return m
}

type BadRequestJSONResponse Error

type NotFoundJSONResponse Error

type ServerErrorJSONResponse Error

type UnauthorizedJSONResponse Error

type PaymentHealthzRequestObject struct {
}

type PaymentHealthzResponseObject interface {
	VisitPaymentHealthzResponse(w http.ResponseWriter) error
}

type PaymentHealthz200JSONResponse struct {
	Status PaymentHealthz200JSONResponseBodyStatus `json:"status"`
}

func (response PaymentHealthz200JSONResponse) VisitPaymentHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PaymentReadyzRequestObject struct {
}

type PaymentReadyzResponseObject interface {
	VisitPaymentReadyzResponse(w http.ResponseWriter) error
}

type PaymentReadyz200JSONResponse struct {
	Status PaymentReadyz200JSONResponseBodyStatus `json:"status"`
}

func (response PaymentReadyz200JSONResponse) VisitPaymentReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PaymentReadyz503JSONResponse Error

func (response PaymentReadyz503JSONResponse) VisitPaymentReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePaymentRequestObject struct {
	Params CreatePaymentParams
	Body   *CreatePaymentJSONRequestBody
}

type CreatePaymentResponseObject interface {
	VisitCreatePaymentResponse(w http.ResponseWriter) error
}

type CreatePayment201JSONResponse struct {
	// AmountMinor Read from the booking, in the currency's minor unit. Never client-supplied.
	AmountMinor int `json:"amount_minor"`

	// BookingId UUIDv7, string-typed everywhere
	//
	// Examples: 01912d5a-7f3e-7c1a-9b2e-3f4a5b6c7d8e
	BookingId Uuid `json:"booking_id"`

	// ClientSecret Stripe PaymentIntent client secret. Returned once, on creation only;
	// never persisted by us and never present on GET responses.
	ClientSecret string    `json:"client_secret"`
	CreatedAt    time.Time `json:"created_at"`
	Currency     string    `json:"currency"`

	// FailureCode Stripe's decline code when status is failed, e.g. card_declined
	FailureCode *string `json:"failure_code,omitempty"`

	// Id UUIDv7, string-typed everywhere
	//
	// Examples: 01912d5a-7f3e-7c1a-9b2e-3f4a5b6c7d8e
	Id       Uuid                                     `json:"id"`
	Provider CreatePayment201JSONResponseBodyProvider `json:"provider"`

	// ProviderPaymentId Stripe PaymentIntent id, e.g. pi_3Abc...
	ProviderPaymentId string `json:"provider_payment_id"`

	// Status pending   — PaymentIntent created, outcome unknown
	// succeeded — Stripe confirmed the charge (via webhook); terminal
	// failed    — Stripe declined or the intent was cancelled; terminal
	Status    PaymentStatus `json:"status"`
	UpdatedAt time.Time     `json:"updated_at"`
}

func (response CreatePayment201JSONResponse) VisitCreatePaymentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePayment400JSONResponse struct{ BadRequestJSONResponse }

func (response CreatePayment400JSONResponse) VisitCreatePaymentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePayment401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreatePayment401JSONResponse) VisitCreatePaymentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePayment404JSONResponse Error

func (response CreatePayment404JSONResponse) VisitCreatePaymentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePayment409JSONResponse Error

func (response CreatePayment409JSONResponse) VisitCreatePaymentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePayment422JSONResponse Error

func (response CreatePayment422JSONResponse) VisitCreatePaymentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePayment500JSONResponse struct{ ServerErrorJSONResponse }

func (response CreatePayment500JSONResponse) VisitCreatePaymentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePayment502JSONResponse Error

func (response CreatePayment502JSONResponse) VisitCreatePaymentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type GetPaymentRequestObject struct {
	PaymentId Uuid `json:"payment_id"`
	Params    GetPaymentParams
}

type GetPaymentResponseObject interface {
	VisitGetPaymentResponse(w http.ResponseWriter) error
}

type GetPayment200JSONResponse Payment

func (response GetPayment200JSONResponse) VisitGetPaymentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPayment401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetPayment401JSONResponse) VisitGetPaymentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetPayment403JSONResponse Error

func (response GetPayment403JSONResponse) VisitGetPaymentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetPayment404JSONResponse struct{ NotFoundJSONResponse }

func (response GetPayment404JSONResponse) VisitGetPaymentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetPayment500JSONResponse struct{ ServerErrorJSONResponse }

func (response GetPayment500JSONResponse) VisitGetPaymentResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type HandleStripeWebhookRequestObject struct {
	Params HandleStripeWebhookParams
	Body   *HandleStripeWebhookJSONRequestBody
}

type HandleStripeWebhookResponseObject interface {
	VisitHandleStripeWebhookResponse(w http.ResponseWriter) error
}

type HandleStripeWebhook200JSONResponse struct {
	Received HandleStripeWebhook200JSONResponseBodyReceived `json:"received"`
}

func (response HandleStripeWebhook200JSONResponse) VisitHandleStripeWebhookResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type HandleStripeWebhook400JSONResponse Error

func (response HandleStripeWebhook400JSONResponse) VisitHandleStripeWebhookResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type HandleStripeWebhook500JSONResponse struct{ ServerErrorJSONResponse }

func (response HandleStripeWebhook500JSONResponse) VisitHandleStripeWebhookResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// PaymentHealthz Liveness probe
	// (GET /healthz)
	PaymentHealthz(ctx context.Context, request PaymentHealthzRequestObject) (PaymentHealthzResponseObject, error)
	// PaymentReadyz Readiness probe — checks database and broker connectivity
	// (GET /readyz)
	PaymentReadyz(ctx context.Context, request PaymentReadyzRequestObject) (PaymentReadyzResponseObject, error)
	// CreatePayment Start a payment for a held booking
	// (POST /v1/payments)
	CreatePayment(ctx context.Context, request CreatePaymentRequestObject) (CreatePaymentResponseObject, error)
	// GetPayment Get a payment's status
	// (GET /v1/payments/{payment_id})
	GetPayment(ctx context.Context, request GetPaymentRequestObject) (GetPaymentResponseObject, error)
	// HandleStripeWebhook Stripe payment outcome callback
	// (POST /v1/webhooks/stripe)
	HandleStripeWebhook(ctx context.Context, request HandleStripeWebhookRequestObject) (HandleStripeWebhookResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// PaymentHealthz operation middleware
func (sh *strictHandler) PaymentHealthz(w http.ResponseWriter, r *http.Request) {
	var request PaymentHealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PaymentHealthz(ctx, request.(PaymentHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PaymentHealthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PaymentHealthzResponseObject); ok {
		if err := validResponse.VisitPaymentHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PaymentReadyz operation middleware
func (sh *strictHandler) PaymentReadyz(w http.ResponseWriter, r *http.Request) {
	var request PaymentReadyzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PaymentReadyz(ctx, request.(PaymentReadyzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PaymentReadyz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PaymentReadyzResponseObject); ok {
		if err := validResponse.VisitPaymentReadyzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreatePayment operation middleware
func (sh *strictHandler) CreatePayment(w http.ResponseWriter, r *http.Request, params CreatePaymentParams) {
	var request CreatePaymentRequestObject

	request.Params = params

	var body CreatePaymentJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePayment(ctx, request.(CreatePaymentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePayment")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreatePaymentResponseObject); ok {
		if err := validResponse.VisitCreatePaymentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPayment operation middleware
func (sh *strictHandler) GetPayment(w http.ResponseWriter, r *http.Request, paymentId Uuid, params GetPaymentParams) {
	var request GetPaymentRequestObject

	request.PaymentId = paymentId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPayment(ctx, request.(GetPaymentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPayment")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPaymentResponseObject); ok {
		if err := validResponse.VisitGetPaymentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// HandleStripeWebhook operation middleware
func (sh *strictHandler) HandleStripeWebhook(w http.ResponseWriter, r *http.Request, params HandleStripeWebhookParams) {
	var request HandleStripeWebhookRequestObject

	request.Params = params

	var body HandleStripeWebhookJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.HandleStripeWebhook(ctx, request.(HandleStripeWebhookRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HandleStripeWebhook")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HandleStripeWebhookResponseObject); ok {
		if err := validResponse.VisitHandleStripeWebhookResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
