//go:build go1.22

// Package booking provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package booking

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BookingStatus.
const (
	Cancelled BookingStatus = "cancelled"
	Confirmed BookingStatus = "confirmed"
	Held      BookingStatus = "held"
)

// Valid indicates whether the value is a known member of the BookingStatus enum.
func (e BookingStatus) Valid() bool {
	switch e {
	case Cancelled:
		return true
	case Confirmed:
		return true
	case Held:
		return true
	default:
		return false
	}
}

// Defines values for ErrorErrorCode.
const (
	ErrorErrorCodeAvailabilityUnavailable ErrorErrorCode = "availability_unavailable"
	ErrorErrorCodeBookingNotFound         ErrorErrorCode = "booking_not_found"
	ErrorErrorCodeIdempotencyKeyReuse     ErrorErrorCode = "idempotency_key_reuse"
	ErrorErrorCodeInternalError           ErrorErrorCode = "internal_error"
	ErrorErrorCodeInvalidTimeWindow       ErrorErrorCode = "invalid_time_window"
	ErrorErrorCodePartyExceedsCapacity    ErrorErrorCode = "party_exceeds_capacity"
	ErrorErrorCodeProductNotFound         ErrorErrorCode = "product_not_found"
	ErrorErrorCodeSlotUnavailable         ErrorErrorCode = "slot_unavailable"
	ErrorErrorCodeUnauthenticated         ErrorErrorCode = "unauthenticated"
	ErrorErrorCodeUnauthorized            ErrorErrorCode = "unauthorized"
	ErrorErrorCodeValidationFailed        ErrorErrorCode = "validation_failed"
)

// Valid indicates whether the value is a known member of the ErrorErrorCode enum.
func (e ErrorErrorCode) Valid() bool {
	switch e {
	case ErrorErrorCodeAvailabilityUnavailable:
		return true
	case ErrorErrorCodeBookingNotFound:
		return true
	case ErrorErrorCodeIdempotencyKeyReuse:
		return true
	case ErrorErrorCodeInternalError:
		return true
	case ErrorErrorCodeInvalidTimeWindow:
		return true
	case ErrorErrorCodePartyExceedsCapacity:
		return true
	case ErrorErrorCodeProductNotFound:
		return true
	case ErrorErrorCodeSlotUnavailable:
		return true
	case ErrorErrorCodeUnauthenticated:
		return true
	case ErrorErrorCodeUnauthorized:
		return true
	case ErrorErrorCodeValidationFailed:
		return true
	default:
		return false
	}
}

// Defines values for BookingHealthz200JSONResponseBodyStatus.
const (
	BookingHealthz200JSONResponseBodyStatusOk BookingHealthz200JSONResponseBodyStatus = "ok"
)

// Valid indicates whether the value is a known member of the BookingHealthz200JSONResponseBodyStatus enum.
func (e BookingHealthz200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case BookingHealthz200JSONResponseBodyStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for BookingReadyz200JSONResponseBodyStatus.
const (
	BookingReadyz200JSONResponseBodyStatusOk BookingReadyz200JSONResponseBodyStatus = "ok"
)

// Valid indicates whether the value is a known member of the BookingReadyz200JSONResponseBodyStatus enum.
func (e BookingReadyz200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case BookingReadyz200JSONResponseBodyStatusOk:
		return true
	default:
		return false
	}
}

// Booking defines model for Booking.
type Booking struct {
	CancellationReason *string   `json:"cancellation_reason,omitempty"`
	CreatedAt          time.Time `json:"created_at"`
	Currency           string    `json:"currency"`

	// CustomerId From the JWT `sub` claim — never client-supplied
	CustomerId Uuid      `json:"customer_id"`
	EndsAt     time.Time `json:"ends_at"`

	// HoldExpiresAt When an unpaid `held` booking is auto-cancelled and its slot freed. Null once
	// confirmed or cancelled.
	HoldExpiresAt *time.Time `json:"hold_expires_at,omitempty"`

	// Id UUIDv7, string-typed everywhere
	//
	// Examples: 01912d5a-7f3e-7c1a-9b2e-3f4a5b6c7d8e
	Id        Uuid `json:"id"`
	PartySize int  `json:"party_size"`

	// ProductId UUIDv7, string-typed everywhere
	//
	// Examples: 01912d5a-7f3e-7c1a-9b2e-3f4a5b6c7d8e
	ProductId Uuid `json:"product_id"`

	// ReservationId Null once released
	ReservationId *Uuid `json:"reservation_id,omitempty"`

	// ResourceId The resource Availability holds on this booking's behalf
	ResourceId Uuid      `json:"resource_id"`
	StartsAt   time.Time `json:"starts_at"`

	// Status held      — slot reserved, TTL running, awaiting payment
	// confirmed — payment succeeded; the booking is real
	// cancelled — terminal; slot released. Reached from held (payment failed, TTL expired,
	//             or customer cancelled) or from confirmed (customer cancelled).
	Status BookingStatus `json:"status"`

	// TotalMinor Authoritative amount to charge, in the currency's minor unit
	TotalMinor int       `json:"total_minor"`
	UpdatedAt  time.Time `json:"updated_at"`
}

// BookingStatus held      — slot reserved, TTL running, awaiting payment
// confirmed — payment succeeded; the booking is real
// cancelled — terminal; slot released. Reached from held (payment failed, TTL expired,
//
//	or customer cancelled) or from confirmed (customer cancelled).
type BookingStatus string

// Error defines model for Error.
type Error struct {
	Error struct {
		Code          ErrorErrorCode `json:"code"`
		CorrelationId string         `json:"correlation_id"`
		Details       *[]struct {
			Field string `json:"field"`
			Issue string `json:"issue"`
		} `json:"details,omitempty"`
		Message string `json:"message"`
	} `json:"error"`
}

// ErrorErrorCode defines model for Error.Error.Code.
type ErrorErrorCode string

// Uuid UUIDv7, string-typed everywhere
//
// Examples: 01912d5a-7f3e-7c1a-9b2e-3f4a5b6c7d8e
type Uuid = openapi_types.UUID

// CorrelationId defines model for CorrelationId.
type CorrelationId = string

// Cursor defines model for Cursor.
type Cursor = string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// Limit defines model for Limit.
type Limit = int

// BadRequest defines model for BadRequest.
type BadRequest = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// BookingHealthz200JSONResponseBodyStatus defines parameters for BookingHealthz.
type BookingHealthz200JSONResponseBodyStatus string

// BookingReadyz200JSONResponseBodyStatus defines parameters for BookingReadyz.
type BookingReadyz200JSONResponseBodyStatus string

// ListBookingsParams defines parameters for ListBookings.
type ListBookingsParams struct {
	Limit  *Limit         `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *Cursor        `form:"cursor,omitempty" json:"cursor,omitempty"`
	Status *BookingStatus `form:"status,omitempty" json:"status,omitempty"`

	// XCorrelationId Propagated unchanged through every downstream call, event, log line, and span.
	XCorrelationId *CorrelationId `json:"X-Correlation-Id,omitempty"`
}

// CreateBookingJSONBody defines parameters for CreateBooking.
type CreateBookingJSONBody struct {
	// EndsAt Exclusive. UTC. Must be strictly after starts_at.
	EndsAt time.Time `json:"ends_at"`

	// PartySize Must not exceed the product's capacity
	PartySize int `json:"party_size"`

	// ProductId UUIDv7, string-typed everywhere
	//
	// Examples: 01912d5a-7f3e-7c1a-9b2e-3f4a5b6c7d8e
	ProductId Uuid `json:"product_id"`

	// StartsAt Inclusive. UTC.
	StartsAt time.Time `json:"starts_at"`
}

// CreateBookingParams defines parameters for CreateBooking.
type CreateBookingParams struct {
	// XCorrelationId Propagated unchanged through every downstream call, event, log line, and span.
	XCorrelationId *CorrelationId `json:"X-Correlation-Id,omitempty"`

	// IdempotencyKey Client-generated unique key. A retried request with the same key and body returns the
	// original booking instead of creating a second hold on the same slot.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// GetBookingParams defines parameters for GetBooking.
type GetBookingParams struct {
	// XCorrelationId Propagated unchanged through every downstream call, event, log line, and span.
	XCorrelationId *CorrelationId `json:"X-Correlation-Id,omitempty"`
}

// CancelBookingJSONBody defines parameters for CancelBooking.
type CancelBookingJSONBody struct {
	Reason *string `json:"reason,omitempty"`
}

// CancelBookingParams defines parameters for CancelBooking.
type CancelBookingParams struct {
	// XCorrelationId Propagated unchanged through every downstream call, event, log line, and span.
	XCorrelationId *CorrelationId `json:"X-Correlation-Id,omitempty"`
}

// CreateBookingJSONRequestBody defines body for CreateBooking for application/json ContentType.
type CreateBookingJSONRequestBody CreateBookingJSONBody

// CancelBookingJSONRequestBody defines body for CancelBooking for application/json ContentType.
type CancelBookingJSONRequestBody CancelBookingJSONBody

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// BookingHealthz Liveness probe
	//
	// Corresponds with GET /healthz (the `BookingHealthz` operationId).
	BookingHealthz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// BookingReadyz Readiness probe — checks database and broker connectivity
	//
	// Corresponds with GET /readyz (the `BookingReadyz` operationId).
	BookingReadyz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListBookings List the caller's own bookings, newest first
	//
	// Scoped to the customer in the JWT claims. Never accepts a customer id parameter.
	//
	// Corresponds with GET /v1/bookings (the `ListBookings` operationId).
	ListBookings(ctx context.Context, params *ListBookingsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateBookingWithBody Hold a slot — the first step of the saga
	//
	// Creates a booking in `held` state and reserves the window through Availability.
	// The hold expires at `hold_expires_at` (BOOKING_HOLD_TTL_SECONDS, default 900s) unless
	// payment confirms it first — this is what stops abandoned checkouts from locking
	// inventory forever.
	//
	// If the window is already taken, Availability's exclusion constraint fires and this
	// returns `409 slot_unavailable`. A prior successful availability query is NOT a
	// guarantee; another customer can win the race in between.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/bookings (the `CreateBooking` operationId).
	CreateBookingWithBody(ctx context.Context, params *CreateBookingParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateBooking Hold a slot — the first step of the saga
	//
	// Creates a booking in `held` state and reserves the window through Availability.
	// The hold expires at `hold_expires_at` (BOOKING_HOLD_TTL_SECONDS, default 900s) unless
	// payment confirms it first — this is what stops abandoned checkouts from locking
	// inventory forever.
	//
	// If the window is already taken, Availability's exclusion constraint fires and this
	// returns `409 slot_unavailable`. A prior successful availability query is NOT a
	// guarantee; another customer can win the race in between.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/bookings (the `CreateBooking` operationId).
	CreateBooking(ctx context.Context, params *CreateBookingParams, body CreateBookingJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetBooking Get one booking
	//
	// Corresponds with GET /v1/bookings/{booking_id} (the `GetBooking` operationId).
	GetBooking(ctx context.Context, bookingId Uuid, params *GetBookingParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CancelBookingWithBody Cancel a booking and release its slot
	//
	// Moves the booking to `cancelled` and releases the reservation (compensation). Emits
	// `BookingCancelled`. Idempotent: cancelling an already-cancelled booking returns 200.
	//
	// Refund policy for confirmed bookings is NOT modelled here — see the cancellation
	// stories in docs/stories/booking-domain-rules.md. Until that lands, cancelling a
	// confirmed booking frees the slot but triggers no refund.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/bookings/{booking_id}/actions/cancel (the `CancelBooking` operationId).
	CancelBookingWithBody(ctx context.Context, bookingId Uuid, params *CancelBookingParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CancelBooking Cancel a booking and release its slot
	//
	// Moves the booking to `cancelled` and releases the reservation (compensation). Emits
	// `BookingCancelled`. Idempotent: cancelling an already-cancelled booking returns 200.
	//
	// Refund policy for confirmed bookings is NOT modelled here — see the cancellation
	// stories in docs/stories/booking-domain-rules.md. Until that lands, cancelling a
	// confirmed booking frees the slot but triggers no refund.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/bookings/{booking_id}/actions/cancel (the `CancelBooking` operationId).
	CancelBooking(ctx context.Context, bookingId Uuid, params *CancelBookingParams, body CancelBookingJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// BookingHealthz Liveness probe
//
// Corresponds with GET /healthz (the `BookingHealthz` operationId).
func (c *Client) BookingHealthz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBookingHealthzRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// BookingReadyz Readiness probe — checks database and broker connectivity
//
// Corresponds with GET /readyz (the `BookingReadyz` operationId).
func (c *Client) BookingReadyz(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBookingReadyzRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListBookings List the caller's own bookings, newest first
//
// Scoped to the customer in the JWT claims. Never accepts a customer id parameter.
//
// Corresponds with GET /v1/bookings (the `ListBookings` operationId).
func (c *Client) ListBookings(ctx context.Context, params *ListBookingsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListBookingsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateBookingWithBody Hold a slot — the first step of the saga
//
// Creates a booking in `held` state and reserves the window through Availability.
// The hold expires at `hold_expires_at` (BOOKING_HOLD_TTL_SECONDS, default 900s) unless
// payment confirms it first — this is what stops abandoned checkouts from locking
// inventory forever.
//
// If the window is already taken, Availability's exclusion constraint fires and this
// returns `409 slot_unavailable`. A prior successful availability query is NOT a
// guarantee; another customer can win the race in between.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/bookings (the `CreateBooking` operationId).
func (c *Client) CreateBookingWithBody(ctx context.Context, params *CreateBookingParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateBookingRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateBooking Hold a slot — the first step of the saga
//
// Creates a booking in `held` state and reserves the window through Availability.
// The hold expires at `hold_expires_at` (BOOKING_HOLD_TTL_SECONDS, default 900s) unless
// payment confirms it first — this is what stops abandoned checkouts from locking
// inventory forever.
//
// If the window is already taken, Availability's exclusion constraint fires and this
// returns `409 slot_unavailable`. A prior successful availability query is NOT a
// guarantee; another customer can win the race in between.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/bookings (the `CreateBooking` operationId).
func (c *Client) CreateBooking(ctx context.Context, params *CreateBookingParams, body CreateBookingJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateBookingRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetBooking Get one booking
//
// Corresponds with GET /v1/bookings/{booking_id} (the `GetBooking` operationId).
func (c *Client) GetBooking(ctx context.Context, bookingId Uuid, params *GetBookingParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetBookingRequest(c.Server, bookingId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CancelBookingWithBody Cancel a booking and release its slot
//
// Moves the booking to `cancelled` and releases the reservation (compensation). Emits
// `BookingCancelled`. Idempotent: cancelling an already-cancelled booking returns 200.
//
// Refund policy for confirmed bookings is NOT modelled here — see the cancellation
// stories in docs/stories/booking-domain-rules.md. Until that lands, cancelling a
// confirmed booking frees the slot but triggers no refund.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/bookings/{booking_id}/actions/cancel (the `CancelBooking` operationId).
func (c *Client) CancelBookingWithBody(ctx context.Context, bookingId Uuid, params *CancelBookingParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCancelBookingRequestWithBody(c.Server, bookingId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CancelBooking Cancel a booking and release its slot
//
// Moves the booking to `cancelled` and releases the reservation (compensation). Emits
// `BookingCancelled`. Idempotent: cancelling an already-cancelled booking returns 200.
//
// Refund policy for confirmed bookings is NOT modelled here — see the cancellation
// stories in docs/stories/booking-domain-rules.md. Until that lands, cancelling a
// confirmed booking frees the slot but triggers no refund.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/bookings/{booking_id}/actions/cancel (the `CancelBooking` operationId).
func (c *Client) CancelBooking(ctx context.Context, bookingId Uuid, params *CancelBookingParams, body CancelBookingJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCancelBookingRequest(c.Server, bookingId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewBookingHealthzRequest constructs an http.Request for the BookingHealthz method
func NewBookingHealthzRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/healthz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewBookingReadyzRequest constructs an http.Request for the BookingReadyz method
func NewBookingReadyzRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/readyz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListBookingsRequest constructs an http.Request for the ListBookings method
func NewListBookingsRequest(server string, params *ListBookingsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/bookings")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "cursor", *params.Cursor, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Status != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "status", *params.Status, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.XCorrelationId != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Correlation-Id", *params.XCorrelationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Correlation-Id", headerParam0)
		}

	}

	return req, nil
}

// NewCreateBookingRequest calls the generic CreateBooking builder with application/json body
func NewCreateBookingRequest(server string, params *CreateBookingParams, body CreateBookingJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateBookingRequestWithBody(server, params, "application/json", bodyReader)
}

// NewCreateBookingRequestWithBody constructs an http.Request for the CreateBooking method, with any body, and a specified content type
func NewCreateBookingRequestWithBody(server string, params *CreateBookingParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/bookings")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.XCorrelationId != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Correlation-Id", *params.XCorrelationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Correlation-Id", headerParam0)
		}

		var headerParam1 string

		headerParam1, err = runtime.StyleParamWithOptions("simple", false, "Idempotency-Key", params.IdempotencyKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Idempotency-Key", headerParam1)

	}

	return req, nil
}

// NewGetBookingRequest constructs an http.Request for the GetBooking method
func NewGetBookingRequest(server string, bookingId Uuid, params *GetBookingParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "booking_id", bookingId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/bookings/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.XCorrelationId != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Correlation-Id", *params.XCorrelationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Correlation-Id", headerParam0)
		}

	}

	return req, nil
}

// NewCancelBookingRequest calls the generic CancelBooking builder with application/json body
func NewCancelBookingRequest(server string, bookingId Uuid, params *CancelBookingParams, body CancelBookingJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCancelBookingRequestWithBody(server, bookingId, params, "application/json", bodyReader)
}

// NewCancelBookingRequestWithBody constructs an http.Request for the CancelBooking method, with any body, and a specified content type
func NewCancelBookingRequestWithBody(server string, bookingId Uuid, params *CancelBookingParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "booking_id", bookingId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/bookings/%s/actions/cancel", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.XCorrelationId != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-Correlation-Id", *params.XCorrelationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Correlation-Id", headerParam0)
		}

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// BookingHealthzWithResponse Liveness probe
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /healthz (the `BookingHealthz` operationId).
	BookingHealthzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*BookingHealthzResponse, error)

	// BookingReadyzWithResponse Readiness probe — checks database and broker connectivity
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /readyz (the `BookingReadyz` operationId).
	BookingReadyzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*BookingReadyzResponse, error)

	// ListBookingsWithResponse List the caller's own bookings, newest first
	//
	// Scoped to the customer in the JWT claims. Never accepts a customer id parameter.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v1/bookings (the `ListBookings` operationId).
	ListBookingsWithResponse(ctx context.Context, params *ListBookingsParams, reqEditors ...RequestEditorFn) (*ListBookingsResponse, error)

	// CreateBookingWithBodyWithResponse Hold a slot — the first step of the saga
	//
	// Creates a booking in `held` state and reserves the window through Availability.
	// The hold expires at `hold_expires_at` (BOOKING_HOLD_TTL_SECONDS, default 900s) unless
	// payment confirms it first — this is what stops abandoned checkouts from locking
	// inventory forever.
	//
	// If the window is already taken, Availability's exclusion constraint fires and this
	// returns `409 slot_unavailable`. A prior successful availability query is NOT a
	// guarantee; another customer can win the race in between.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/bookings (the `CreateBooking` operationId).
	CreateBookingWithBodyWithResponse(ctx context.Context, params *CreateBookingParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateBookingResponse, error)

	// CreateBookingWithResponse Hold a slot — the first step of the saga
	//
	// Creates a booking in `held` state and reserves the window through Availability.
	// The hold expires at `hold_expires_at` (BOOKING_HOLD_TTL_SECONDS, default 900s) unless
	// payment confirms it first — this is what stops abandoned checkouts from locking
	// inventory forever.
	//
	// If the window is already taken, Availability's exclusion constraint fires and this
	// returns `409 slot_unavailable`. A prior successful availability query is NOT a
	// guarantee; another customer can win the race in between.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/bookings (the `CreateBooking` operationId).
	CreateBookingWithResponse(ctx context.Context, params *CreateBookingParams, body CreateBookingJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateBookingResponse, error)

	// GetBookingWithResponse Get one booking
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v1/bookings/{booking_id} (the `GetBooking` operationId).
	GetBookingWithResponse(ctx context.Context, bookingId Uuid, params *GetBookingParams, reqEditors ...RequestEditorFn) (*GetBookingResponse, error)

	// CancelBookingWithBodyWithResponse Cancel a booking and release its slot
	//
	// Moves the booking to `cancelled` and releases the reservation (compensation). Emits
	// `BookingCancelled`. Idempotent: cancelling an already-cancelled booking returns 200.
	//
	// Refund policy for confirmed bookings is NOT modelled here — see the cancellation
	// stories in docs/stories/booking-domain-rules.md. Until that lands, cancelling a
	// confirmed booking frees the slot but triggers no refund.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/bookings/{booking_id}/actions/cancel (the `CancelBooking` operationId).
	CancelBookingWithBodyWithResponse(ctx context.Context, bookingId Uuid, params *CancelBookingParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CancelBookingResponse, error)

	// CancelBookingWithResponse Cancel a booking and release its slot
	//
	// Moves the booking to `cancelled` and releases the reservation (compensation). Emits
	// `BookingCancelled`. Idempotent: cancelling an already-cancelled booking returns 200.
	//
	// Refund policy for confirmed bookings is NOT modelled here — see the cancellation
	// stories in docs/stories/booking-domain-rules.md. Until that lands, cancelling a
	// confirmed booking frees the slot but triggers no refund.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/bookings/{booking_id}/actions/cancel (the `CancelBooking` operationId).
	CancelBookingWithResponse(ctx context.Context, bookingId Uuid, params *CancelBookingParams, body CancelBookingJSONRequestBody, reqEditors ...RequestEditorFn) (*CancelBookingResponse, error)
}

type BookingHealthzResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		Status BookingHealthz200JSONResponseBodyStatus `json:"status"`
	}
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r BookingHealthzResponse) GetJSON200() *struct {
	Status BookingHealthz200JSONResponseBodyStatus `json:"status"`
} {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r BookingHealthzResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r BookingHealthzResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BookingHealthzResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r BookingHealthzResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type BookingReadyzResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		Status BookingReadyz200JSONResponseBodyStatus `json:"status"`
	}
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r BookingReadyzResponse) GetJSON200() *struct {
	Status BookingReadyz200JSONResponseBodyStatus `json:"status"`
} {
	return r.JSON200
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r BookingReadyzResponse) GetJSON503() *Error {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r BookingReadyzResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r BookingReadyzResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BookingReadyzResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r BookingReadyzResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListBookingsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *struct {
		Data       []Booking `json:"data"`
		NextCursor *string   `json:"next_cursor"`
	}
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListBookingsResponse) GetJSON200() *struct {
	Data       []Booking `json:"data"`
	NextCursor *string   `json:"next_cursor"`
} {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r ListBookingsResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetBody returns the raw response body bytes
func (r ListBookingsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListBookingsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListBookingsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListBookingsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateBookingResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *Booking
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Error
	// JSON422 the response for an HTTP 422 `application/json` response
	JSON422 *Error
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *Error
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r CreateBookingResponse) GetJSON201() *Booking {
	return r.JSON201
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r CreateBookingResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r CreateBookingResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r CreateBookingResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r CreateBookingResponse) GetJSON409() *Error {
	return r.JSON409
}

// GetJSON422 returns the response for an HTTP 422 `application/json` response
func (r CreateBookingResponse) GetJSON422() *Error {
	return r.JSON422
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r CreateBookingResponse) GetJSON503() *Error {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r CreateBookingResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreateBookingResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateBookingResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateBookingResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetBookingResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Booking
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetBookingResponse) GetJSON200() *Booking {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r GetBookingResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r GetBookingResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetBookingResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r GetBookingResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetBookingResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetBookingResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetBookingResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CancelBookingResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Booking
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r CancelBookingResponse) GetJSON200() *Booking {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r CancelBookingResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r CancelBookingResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r CancelBookingResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r CancelBookingResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CancelBookingResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CancelBookingResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CancelBookingResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// BookingHealthzWithResponse Liveness probe
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /healthz (the `BookingHealthz` operationId).
func (c *ClientWithResponses) BookingHealthzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*BookingHealthzResponse, error) {
	rsp, err := c.BookingHealthz(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBookingHealthzResponse(rsp)
}

// BookingReadyzWithResponse Readiness probe — checks database and broker connectivity
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /readyz (the `BookingReadyz` operationId).
func (c *ClientWithResponses) BookingReadyzWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*BookingReadyzResponse, error) {
	rsp, err := c.BookingReadyz(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBookingReadyzResponse(rsp)
}

// ListBookingsWithResponse List the caller's own bookings, newest first
//
// Scoped to the customer in the JWT claims. Never accepts a customer id parameter.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /v1/bookings (the `ListBookings` operationId).
func (c *ClientWithResponses) ListBookingsWithResponse(ctx context.Context, params *ListBookingsParams, reqEditors ...RequestEditorFn) (*ListBookingsResponse, error) {
	rsp, err := c.ListBookings(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListBookingsResponse(rsp)
}

// CreateBookingWithBodyWithResponse Hold a slot — the first step of the saga
//
// Creates a booking in `held` state and reserves the window through Availability.
// The hold expires at `hold_expires_at` (BOOKING_HOLD_TTL_SECONDS, default 900s) unless
// payment confirms it first — this is what stops abandoned checkouts from locking
// inventory forever.
//
// If the window is already taken, Availability's exclusion constraint fires and this
// returns `409 slot_unavailable`. A prior successful availability query is NOT a
// guarantee; another customer can win the race in between.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/bookings (the `CreateBooking` operationId).
func (c *ClientWithResponses) CreateBookingWithBodyWithResponse(ctx context.Context, params *CreateBookingParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateBookingResponse, error) {
	rsp, err := c.CreateBookingWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateBookingResponse(rsp)
}

// CreateBookingWithResponse Hold a slot — the first step of the saga
//
// Creates a booking in `held` state and reserves the window through Availability.
// The hold expires at `hold_expires_at` (BOOKING_HOLD_TTL_SECONDS, default 900s) unless
// payment confirms it first — this is what stops abandoned checkouts from locking
// inventory forever.
//
// If the window is already taken, Availability's exclusion constraint fires and this
// returns `409 slot_unavailable`. A prior successful availability query is NOT a
// guarantee; another customer can win the race in between.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/bookings (the `CreateBooking` operationId).
func (c *ClientWithResponses) CreateBookingWithResponse(ctx context.Context, params *CreateBookingParams, body CreateBookingJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateBookingResponse, error) {
	rsp, err := c.CreateBooking(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateBookingResponse(rsp)
}

// GetBookingWithResponse Get one booking
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /v1/bookings/{booking_id} (the `GetBooking` operationId).
func (c *ClientWithResponses) GetBookingWithResponse(ctx context.Context, bookingId Uuid, params *GetBookingParams, reqEditors ...RequestEditorFn) (*GetBookingResponse, error) {
	rsp, err := c.GetBooking(ctx, bookingId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetBookingResponse(rsp)
}

// CancelBookingWithBodyWithResponse Cancel a booking and release its slot
//
// Moves the booking to `cancelled` and releases the reservation (compensation). Emits
// `BookingCancelled`. Idempotent: cancelling an already-cancelled booking returns 200.
//
// Refund policy for confirmed bookings is NOT modelled here — see the cancellation
// stories in docs/stories/booking-domain-rules.md. Until that lands, cancelling a
// confirmed booking frees the slot but triggers no refund.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/bookings/{booking_id}/actions/cancel (the `CancelBooking` operationId).
func (c *ClientWithResponses) CancelBookingWithBodyWithResponse(ctx context.Context, bookingId Uuid, params *CancelBookingParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CancelBookingResponse, error) {
	rsp, err := c.CancelBookingWithBody(ctx, bookingId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCancelBookingResponse(rsp)
}

// CancelBookingWithResponse Cancel a booking and release its slot
//
// Moves the booking to `cancelled` and releases the reservation (compensation). Emits
// `BookingCancelled`. Idempotent: cancelling an already-cancelled booking returns 200.
//
// Refund policy for confirmed bookings is NOT modelled here — see the cancellation
// stories in docs/stories/booking-domain-rules.md. Until that lands, cancelling a
// confirmed booking frees the slot but triggers no refund.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/bookings/{booking_id}/actions/cancel (the `CancelBooking` operationId).
func (c *ClientWithResponses) CancelBookingWithResponse(ctx context.Context, bookingId Uuid, params *CancelBookingParams, body CancelBookingJSONRequestBody, reqEditors ...RequestEditorFn) (*CancelBookingResponse, error) {
	rsp, err := c.CancelBooking(ctx, bookingId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCancelBookingResponse(rsp)
}

// ParseBookingHealthzResponse parses an HTTP response from a BookingHealthzWithResponse call
func ParseBookingHealthzResponse(rsp *http.Response) (*BookingHealthzResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BookingHealthzResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Status BookingHealthz200JSONResponseBodyStatus `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseBookingReadyzResponse parses an HTTP response from a BookingReadyzWithResponse call
func ParseBookingReadyzResponse(rsp *http.Response) (*BookingReadyzResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BookingReadyzResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Status BookingReadyz200JSONResponseBodyStatus `json:"status"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseListBookingsResponse parses an HTTP response from a ListBookingsWithResponse call
func ParseListBookingsResponse(rsp *http.Response) (*ListBookingsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListBookingsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data       []Booking `json:"data"`
			NextCursor *string   `json:"next_cursor"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseCreateBookingResponse parses an HTTP response from a CreateBookingWithResponse call
func ParseCreateBookingResponse(rsp *http.Response) (*CreateBookingResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateBookingResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Booking
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseGetBookingResponse parses an HTTP response from a GetBookingWithResponse call
func ParseGetBookingResponse(rsp *http.Response) (*GetBookingResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetBookingResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Booking
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseCancelBookingResponse parses an HTTP response from a CancelBookingWithResponse call
func ParseCancelBookingResponse(rsp *http.Response) (*CancelBookingResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CancelBookingResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Booking
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// BookingHealthz Liveness probe
	// (GET /healthz)
	BookingHealthz(w http.ResponseWriter, r *http.Request)
	// BookingReadyz Readiness probe — checks database and broker connectivity
	// (GET /readyz)
	BookingReadyz(w http.ResponseWriter, r *http.Request)
	// ListBookings List the caller's own bookings, newest first
	// (GET /v1/bookings)
	ListBookings(w http.ResponseWriter, r *http.Request, params ListBookingsParams)
	// CreateBooking Hold a slot — the first step of the saga
	// (POST /v1/bookings)
	CreateBooking(w http.ResponseWriter, r *http.Request, params CreateBookingParams)
	// GetBooking Get one booking
	// (GET /v1/bookings/{booking_id})
	GetBooking(w http.ResponseWriter, r *http.Request, bookingId Uuid, params GetBookingParams)
	// CancelBooking Cancel a booking and release its slot
	// (POST /v1/bookings/{booking_id}/actions/cancel)
	CancelBooking(w http.ResponseWriter, r *http.Request, bookingId Uuid, params CancelBookingParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// BookingHealthz operation middleware
func (siw *ServerInterfaceWrapper) BookingHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BookingHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BookingReadyz operation middleware
func (siw *ServerInterfaceWrapper) BookingReadyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BookingReadyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListBookings operation middleware
func (siw *ServerInterfaceWrapper) ListBookings(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListBookingsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "X-Correlation-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Correlation-Id")]; found {
		var XCorrelationId CorrelationId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Correlation-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Correlation-Id", valueList[0], &XCorrelationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Correlation-Id", Err: err})
			return
		}

		params.XCorrelationId = &XCorrelationId

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBookings(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateBooking operation middleware
func (siw *ServerInterfaceWrapper) CreateBooking(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateBookingParams

	headers := r.Header

	// ------------- Optional header parameter "X-Correlation-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Correlation-Id")]; found {
		var XCorrelationId CorrelationId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Correlation-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Correlation-Id", valueList[0], &XCorrelationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Correlation-Id", Err: err})
			return
		}

		params.XCorrelationId = &XCorrelationId

	}

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateBooking(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBooking operation middleware
func (siw *ServerInterfaceWrapper) GetBooking(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "booking_id" -------------
	var bookingId Uuid

	err = runtime.BindStyledParameterWithOptions("simple", "booking_id", r.PathValue("booking_id"), &bookingId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "booking_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetBookingParams

	headers := r.Header

	// ------------- Optional header parameter "X-Correlation-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Correlation-Id")]; found {
		var XCorrelationId CorrelationId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Correlation-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Correlation-Id", valueList[0], &XCorrelationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Correlation-Id", Err: err})
			return
		}

		params.XCorrelationId = &XCorrelationId

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBooking(w, r, bookingId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelBooking operation middleware
func (siw *ServerInterfaceWrapper) CancelBooking(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "booking_id" -------------
	var bookingId Uuid

	err = runtime.BindStyledParameterWithOptions("simple", "booking_id", r.PathValue("booking_id"), &bookingId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "booking_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CancelBookingParams

	headers := r.Header

	// ------------- Optional header parameter "X-Correlation-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Correlation-Id")]; found {
		var XCorrelationId CorrelationId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Correlation-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Correlation-Id", valueList[0], &XCorrelationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Correlation-Id", Err: err})
			return
		}

		params.XCorrelationId = &XCorrelationId

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelBooking(w, r, bookingId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.BookingHealthz)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/readyz", wrapper.BookingReadyz)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/bookings", wrapper.ListBookings)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/bookings", wrapper.CreateBooking)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/bookings/{booking_id}", wrapper.GetBooking)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/bookings/{booking_id}/actions/cancel", wrapper.CancelBooking)

	return m
}

type BadRequestJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type BookingHealthzRequestObject struct {
}

type BookingHealthzResponseObject interface {
	VisitBookingHealthzResponse(w http.ResponseWriter) error
}

type BookingHealthz200JSONResponse struct {
	Status BookingHealthz200JSONResponseBodyStatus `json:"status"`
}

func (response BookingHealthz200JSONResponse) VisitBookingHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type BookingReadyzRequestObject struct {
}

type BookingReadyzResponseObject interface {
	VisitBookingReadyzResponse(w http.ResponseWriter) error
}

type BookingReadyz200JSONResponse struct {
	Status BookingReadyz200JSONResponseBodyStatus `json:"status"`
}

func (response BookingReadyz200JSONResponse) VisitBookingReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type BookingReadyz503JSONResponse Error

func (response BookingReadyz503JSONResponse) VisitBookingReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type ListBookingsRequestObject struct {
	Params ListBookingsParams
}

type ListBookingsResponseObject interface {
	VisitListBookingsResponse(w http.ResponseWriter) error
}

type ListBookings200JSONResponse struct {
	Data       []Booking `json:"data"`
	NextCursor *string   `json:"next_cursor"`
}

func (response ListBookings200JSONResponse) VisitListBookingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListBookings401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListBookings401JSONResponse) VisitListBookingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateBookingRequestObject struct {
	Params CreateBookingParams
	Body   *CreateBookingJSONRequestBody
}

type CreateBookingResponseObject interface {
	VisitCreateBookingResponse(w http.ResponseWriter) error
}

type CreateBooking201JSONResponse Booking

func (response CreateBooking201JSONResponse) VisitCreateBookingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateBooking400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateBooking400JSONResponse) VisitCreateBookingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateBooking401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateBooking401JSONResponse) VisitCreateBookingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateBooking404JSONResponse Error

func (response CreateBooking404JSONResponse) VisitCreateBookingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateBooking409JSONResponse Error

func (response CreateBooking409JSONResponse) VisitCreateBookingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateBooking422JSONResponse Error

func (response CreateBooking422JSONResponse) VisitCreateBookingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type CreateBooking503JSONResponse Error

func (response CreateBooking503JSONResponse) VisitCreateBookingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetBookingRequestObject struct {
	BookingId Uuid `json:"booking_id"`
	Params    GetBookingParams
}

type GetBookingResponseObject interface {
	VisitGetBookingResponse(w http.ResponseWriter) error
}

type GetBooking200JSONResponse Booking

func (response GetBooking200JSONResponse) VisitGetBookingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetBooking401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetBooking401JSONResponse) VisitGetBookingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetBooking403JSONResponse Error

func (response GetBooking403JSONResponse) VisitGetBookingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetBooking404JSONResponse struct{ NotFoundJSONResponse }

func (response GetBooking404JSONResponse) VisitGetBookingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CancelBookingRequestObject struct {
	BookingId Uuid `json:"booking_id"`
	Params    CancelBookingParams
	Body      *CancelBookingJSONRequestBody
}

type CancelBookingResponseObject interface {
	VisitCancelBookingResponse(w http.ResponseWriter) error
}

type CancelBooking200JSONResponse Booking

func (response CancelBooking200JSONResponse) VisitCancelBookingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CancelBooking401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CancelBooking401JSONResponse) VisitCancelBookingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CancelBooking403JSONResponse Error

func (response CancelBooking403JSONResponse) VisitCancelBookingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CancelBooking404JSONResponse struct{ NotFoundJSONResponse }

func (response CancelBooking404JSONResponse) VisitCancelBookingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// BookingHealthz Liveness probe
	// (GET /healthz)
	BookingHealthz(ctx context.Context, request BookingHealthzRequestObject) (BookingHealthzResponseObject, error)
	// BookingReadyz Readiness probe — checks database and broker connectivity
	// (GET /readyz)
	BookingReadyz(ctx context.Context, request BookingReadyzRequestObject) (BookingReadyzResponseObject, error)
	// ListBookings List the caller's own bookings, newest first
	// (GET /v1/bookings)
	ListBookings(ctx context.Context, request ListBookingsRequestObject) (ListBookingsResponseObject, error)
	// CreateBooking Hold a slot — the first step of the saga
	// (POST /v1/bookings)
	CreateBooking(ctx context.Context, request CreateBookingRequestObject) (CreateBookingResponseObject, error)
	// GetBooking Get one booking
	// (GET /v1/bookings/{booking_id})
	GetBooking(ctx context.Context, request GetBookingRequestObject) (GetBookingResponseObject, error)
	// CancelBooking Cancel a booking and release its slot
	// (POST /v1/bookings/{booking_id}/actions/cancel)
	CancelBooking(ctx context.Context, request CancelBookingRequestObject) (CancelBookingResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// BookingHealthz operation middleware
func (sh *strictHandler) BookingHealthz(w http.ResponseWriter, r *http.Request) {
	var request BookingHealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.BookingHealthz(ctx, request.(BookingHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "BookingHealthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(BookingHealthzResponseObject); ok {
		if err := validResponse.VisitBookingHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// BookingReadyz operation middleware
func (sh *strictHandler) BookingReadyz(w http.ResponseWriter, r *http.Request) {
	var request BookingReadyzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.BookingReadyz(ctx, request.(BookingReadyzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "BookingReadyz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(BookingReadyzResponseObject); ok {
		if err := validResponse.VisitBookingReadyzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListBookings operation middleware
func (sh *strictHandler) ListBookings(w http.ResponseWriter, r *http.Request, params ListBookingsParams) {
	var request ListBookingsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListBookings(ctx, request.(ListBookingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListBookings")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListBookingsResponseObject); ok {
		if err := validResponse.VisitListBookingsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateBooking operation middleware
func (sh *strictHandler) CreateBooking(w http.ResponseWriter, r *http.Request, params CreateBookingParams) {
	var request CreateBookingRequestObject

	request.Params = params

	var body CreateBookingJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateBooking(ctx, request.(CreateBookingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateBooking")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateBookingResponseObject); ok {
		if err := validResponse.VisitCreateBookingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetBooking operation middleware
func (sh *strictHandler) GetBooking(w http.ResponseWriter, r *http.Request, bookingId Uuid, params GetBookingParams) {
	var request GetBookingRequestObject

	request.BookingId = bookingId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetBooking(ctx, request.(GetBookingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBooking")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetBookingResponseObject); ok {
		if err := validResponse.VisitGetBookingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CancelBooking operation middleware
func (sh *strictHandler) CancelBooking(w http.ResponseWriter, r *http.Request, bookingId Uuid, params CancelBookingParams) {
	var request CancelBookingRequestObject

	request.BookingId = bookingId
	request.Params = params

	var body CancelBookingJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CancelBooking(ctx, request.(CancelBookingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CancelBooking")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CancelBookingResponseObject); ok {
		if err := validResponse.VisitCancelBookingResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
